### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by ticherhaz** [qwerqy/orobahn#12]
Nk tny sikit boleh, yang language tu fully pakai JS ke? sy newbie nie. mcm yg sy blajar kan, html pastu coding2 skit kat js. 
pastu kalau link dia akan ada index.html. mcm nak buat mcm yg en buat tu?

**Comment by qwerqy** [comment]
hello Hazman, which `language` ? boleh describe lagi tak?

**Comment by ticherhaz** [comment]
hello, ada buat video tutorial tak mcm mana nak apply semua2 tu.? :D

**Comment by qwerqy** [comment]
`Error 402`
